services:
    command.fixture.loader_loader:
        class: Doctrine\Common\DataFixtures\Loader
    command.fixture.loader_purger:
        class: Doctrine\Common\DataFixtures\Purger\MongoDBPurger
    command.fixture.loader_executor:
        class: Doctrine\Common\DataFixtures\Executor\MongoDBExecutor
        arguments:
            - '@doctrine_mongodb.odm.document_manager'
            - '@command.fixture.loader_purger'

    command.fixture.loader:
        class: Chronos\ApiBundle\Command\FixtureLoaderCommand
        arguments:
            - '@command.fixture.loader_executor'
            - '@command.fixture.loader_loader'
            - '@file_locator'
            - '%kernel.bundles%'
        tags:
            - { name: 'console.command', command: 'app:fixture:load' }
        public: false
        
    api.response_factory.json:
        class: Chronos\ApiBundle\Formatter\Response\JsonResponseFactory
        arguments:
            - "@logger"
        public: false
