services:
    command.fixture.loader:
        class: Chronos\ApiBundle\Command\FixtureLoaderCommand
        arguments:
            - '@doctrine_mongodb.odm.document_manager'
            - '@file_locator'
            - '%kernel.bundles%'
        tags:
            - { name: 'console.command', command: 'app:fixture:load' }
        public: false
        
    api.response_factory.json:
        class: Chronos\ApiBundle\Formatter\Response\JsonResponseFactory
        arguments:
            - "@logger"
        public: false
