nelmio_api_doc:
    documentation:
        info:
            title: Chronos
            description: The kairos API
            version: 1.0.0-dev
    areas: # to filter documented routes
        path_patterns:
            - ^/user # Accepts routes under /api except /api/doc
