services:
    UserRepository:
        class: Doctrine\ODM\MongoDB\DocumentRepository
        factory: ['@doctrine_mongodb.odm.document_manager', getRepository]
        arguments:
            - "ChronosUserBundle:SimpleUser"
        public: false
        
    UserProvider:
        class: Chronos\ApiBundle\Provider\GenericDocumentProvider
        arguments:
            - "@UserRepository"
            - "@logger"
        public: false
    
    UserAttributeConverter:
        parent: abstract_api.serializer.property_name_converter
        public: false
        arguments:
            - {'roleEntities': 'roles'}
    user.serializer.object.normalizer:
        parent: abstract_api.serializer.object.normalizer
        public: false
        arguments: 
            - "@UserAttributeConverter"
    user.serializer:
        parent: abstract_api.serializer
        public: false
        arguments:
            index_0: ['@user.serializer.object.normalizer']
    
    UserSerializer:
        class: Chronos\ApiBundle\Formatter\GenericEventDataFormatter
        arguments:
            - "@user.serializer"
            - "json"
            - "@api.response_factory.json"
            - "@logger"
            - {isJson: true}
            - {groups: ['user.id', 'user.username', 'user.roles', 'role.id']}
        public: false
        
    UserDispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        calls:
            - ['addListener', [!php/const Chronos\ApiBundle\Event\ApiControllerEventInterface::EVENT_GET_MULTIPLE, ['@UserProvider', 'provideDocuments'], 10]]
            - ['addListener', [!php/const Chronos\ApiBundle\Event\ApiControllerEventInterface::EVENT_GET_MULTIPLE, ['@UserSerializer', 'format'], 0]]
        public: false
        
    UserController:
        class: Chronos\UserBundle\Controller\SimpleUserController
        arguments:
            - "@UserDispatcher"
        public: true
